source $VIMC/plug/plugins.vim
source $VIMC/configs/autosave.vim
source $VIMC/configs/surround.vim
source $VIMC/configs/vim-which-key.vim
source $VIMC/general/commands-functions.vim
source $VIMC/general/settings.vim
source $VIMC/general/QoL.vim
source $VIMC/keymaps/standard_maps.vim
source $VIMC/keymaps/plugin_maps.vim
